# Generated by Django 5.0 on 2023-12-06 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=150)),
                ('facilityType', models.CharField(blank=True, choices=[('Push Cart', 'Push Cart'), ('Truck', 'Truck')], max_length=9)),
                ('cnn', models.IntegerField()),
                ('locationDescription', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.IntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_coordinates'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='food_trucks.location'),
        ),
    ]
