# Generated by Django 5.0 on 2023-12-08 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(blank=True, max_length=150)),
                ('facilityType', models.CharField(blank=True, choices=[('Push Cart', 'Push Cart'), ('Truck', 'Truck')], max_length=9)),
                ('cnn', models.IntegerField(blank=True)),
                ('locationDescription', models.CharField(blank=True, max_length=150)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('block', models.CharField(blank=True, max_length=150)),
                ('lot', models.CharField(blank=True, max_length=150)),
                ('permit', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(blank=True, choices=[('APPROVED', 'APPROVED'), ('REQUESTED', 'REQUESTED'), ('SUSPEND', 'SUSPEND'), ('EXPIRED', 'EXPIRED'), ('ISSUED', 'ISSUED')], max_length=9)),
                ('foodItems', models.CharField(blank=True, max_length=500)),
                ('x', models.CharField(blank=True, max_length=150)),
                ('y', models.CharField(blank=True, max_length=150)),
                ('daysHours', models.CharField(blank=True, max_length=150)),
                ('NOISent', models.CharField(blank=True, max_length=150)),
                ('schedule', models.CharField(blank=True, max_length=250)),
                ('approved', models.DateTimeField(blank=True, null=True)),
                ('received', models.CharField(blank=True, max_length=150)),
                ('priorPermit', models.IntegerField(blank=True, choices=[(0, 'Option0'), (1, 'Option1')])),
                ('expirationDate', models.DateTimeField(blank=True, null=True)),
                ('firePreventionDistricts', models.CharField(blank=True, max_length=150)),
                ('policeDistricts', models.CharField(blank=True, max_length=150)),
                ('supervisorDistricts', models.CharField(blank=True, max_length=150)),
                ('zipCode', models.CharField(blank=True, max_length=150)),
                ('neighborhoodsOld', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationId', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('latitude', 'longitude'), name='unique_coordinates'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.ForeignKey(db_column='location_id', on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='food_trucks.location'),
        ),
    ]
