# Generated by Django 5.0 on 2023-12-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='locationId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
